version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
    restart: unless-stopped

  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /home/ubuntu/app/uploads:/app/uploads
      - /home/ubuntu/app/processed:/app/processed
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
    restart: unless-stopped
